# remote_theme: MezereonXP/minima
remote_theme: MezereonXP/jekyll-theme-chirpy
title: MezereonXP-Blog
author: MezereonXP
description: This is my blog site.
markdown: kramdown
timezone: +0800
avatar: assets/avatar.jpeg